import sys
import os
import time
import re


def read_onomatopoeia_file(filename):
    cn_onomatopoeias = []
    en_onomatopoeias = {}
    with open(filename, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if '=' in line:
                left_part = line.split('=', 1)[0].strip()
                right_part = line.split('=', 1)[1].strip()
                if left_part and right_part:
                    cn_onomatopoeias.append(left_part)
                    en_onomatopoeias[left_part] = right_part
    return cn_onomatopoeias, en_onomatopoeias


def read_all_dialogs_file(filename):
    with open(filename, 'r', encoding='utf-8') as f:
        return [line.strip() for line in f]


def process_directory(cn_onomatopoeias, en_onomatopoeias, directory_path, all_dialogs, output_filename):
    placeholder_pattern = re.compile(r"\{\{[^}]+\}\}")

    with open(output_filename, 'w', encoding='utf-8') as output_file:
        for filename in os.listdir(directory_path):
            if filename in ("_AutoGeneratedTranslations.txt", "_Substitutions.txt"):
                continue

            full_path = os.path.join(directory_path, filename)

            if not os.path.isfile(full_path):
                continue
                
            print(f"Reading file: {filename}")

            with open(full_path, 'r', encoding='utf-8') as f:
                for line_number, line in enumerate(f, start=1):
                    line = line.strip()

                    if '=' not in line:
                        continue

                    left_part = ""
                    parts = []
                    if line.startswith('r:"'):
                        parts = line.split('"="', 1)
                    else:
                        parts = re.split(r'(?<!\\)=', line, maxsplit=1)
                    if len(parts) > 1:
                        left_part = parts[0]

                    # Must contain at least one {{x}}
                    if not placeholder_pattern.search(left_part):
                        continue

                    # Split by {{x}}
                    parts = placeholder_pattern.split(left_part)

                    for part in parts:
                        part = part.strip()
                        if not part:
                            continue

                        for dialog in all_dialogs:
                            if part in dialog:
                                for cn_onomatopoeia in cn_onomatopoeias:
                                    if cn_onomatopoeia in dialog:
                                        output_file.write(
                                            f"{filename} | Line {line_number} | {left_part} | {cn_onomatopoeia} | {en_onomatopoeias[cn_onomatopoeia]} | {dialog}\n"
                                        )
                                        break
                                break


def main():
    if len(sys.argv) != 5:
        print("Usage: python onomatopoeia_check.py <onomatopoeia_file> <translation_directory> <all_dialogs_file> <output_file>")
        sys.exit(1)
        
    start_time = time.time()

    onomatopoeia_file = sys.argv[1]
    translation_directory = sys.argv[2]
    all_dialogs_file = sys.argv[3]
    output_file = sys.argv[4]

    cn_onomatopoeias, en_onomatopoeias = read_onomatopoeia_file(onomatopoeia_file)
    all_dialogs = read_all_dialogs_file(all_dialogs_file)

    process_directory(cn_onomatopoeias, en_onomatopoeias, translation_directory, all_dialogs, output_file)
    
    end_time = time.time()
    elapsed_time = end_time - start_time
    
    print(f"Operation completed in {elapsed_time:.4f} seconds.")


if __name__ == "__main__":
    main()