import sys
import os
import time
import re

# Start timer
start_time = time.time()

# Check arguments
if len(sys.argv) != 2:
    print("Usage: python text_check.py <directory_path>")
    sys.exit(1)

directory_path = sys.argv[1]
substitutions_filename = "_Substitutions.txt"
auto_generated_filename = "_AutoGeneratedTranslations.txt"
results_filename = "results.txt"

substitutions_path = os.path.join(directory_path, substitutions_filename)
results_path = os.path.join(os.getcwd(), results_filename)  # current directory

first_parts = []
matches = []

# Check directory
if not os.path.isdir(directory_path):
    print(f"Error: Directory '{directory_path}' not found.")
    sys.exit(1)

# Check _Substitutions.txt exists
if not os.path.isfile(substitutions_path):
    print(f"Error: '{substitutions_filename}' not found in '{directory_path}'.")
    sys.exit(1)

# Read _Substitutions.txt and collect left side of "="
with open(substitutions_path, "r", encoding="utf-8") as file1:
    for line in file1:
        line = line.strip()
        parts = line.split("=", 1)
        if len(parts) > 1:
            first_parts.append(parts[0])

# Process all other .txt files in the directory
for filename in os.listdir(directory_path):
    if (
        filename.lower().endswith(".txt")
        and filename != substitutions_filename
        and filename != auto_generated_filename
    ):
        file_path = os.path.join(directory_path, filename)

        try:
            with open(file_path, "r", encoding="utf-8") as file2:
                for line_number, line in enumerate(file2, start=1):
                    line = line.strip()

                    parts = []
                    if line.startswith('r:"'):
                        parts = line.split('"="', 1)
                    else:
                        parts = re.split(r'(?<!\\)=', line, maxsplit=1)

                    if len(parts) > 1:
                        left_side = parts[0]

                        for text in first_parts:
                            if text in left_side:
                                matches.append(
                                    f"{filename} "
                                    f"on line {line_number}: "
                                    f"'{text}' in '{left_side}'"
                                )
        except Exception as e:
            print(f"Error reading '{file_path}': {e}")

# Write results only if matches were found, overwriting any existing file
if matches:
    with open(results_path, "w", encoding="utf-8") as results_file:
        for match in matches:
            results_file.write(match + "\n")

    print(f"Results written to: {results_path}")
else:
    print("No match found.")

# End timer
end_time = time.time()
elapsed_time = end_time - start_time

print(f"Operation completed in {elapsed_time:.4f} seconds.")
